[package]
name = "AdventOfCode2024"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

[dev-dependencies]
criterion = { version = "0.4.0", features=["html_reports"] }
#criterion = { version = "0.5.1" }

[[bench]]
name = "benchmark"
#harness = false
